const express=require('express'); const cors=require('cors'); const jwt=require('jsonwebtoken'); const Database=require('better-sqlite3');
const app=express(); app.use(cors()); app.use(express.json());
const db=new Database('suri.sqlite');
const SECRET=process.env.ADMIN_SECRET||'CHANGE_THIS_ADMIN_SECRET';
db.exec(`CREATE TABLE IF NOT EXISTS tournaments(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,game TEXT NOT NULL,entry_fee INTEGER NOT NULL,prize TEXT,slots INTEGER NOT NULL,start_at TEXT,status TEXT DEFAULT 'OPEN',room_id TEXT,room_password TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS registrations(id INTEGER PRIMARY KEY AUTOINCREMENT,tournament_id INTEGER NOT NULL,player_name TEXT NOT NULL,uid TEXT NOT NULL,team_name TEXT,utr TEXT,status TEXT DEFAULT 'PENDING',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
function admin(req,res,next){try{const h=req.headers.authorization||''; req.user=jwt.verify(h.replace('Bearer ',''),SECRET); next()}catch(e){res.status(401).json({error:'Unauthorized'})}}
app.get('/api/tournaments',(req,res)=>res.json(db.prepare('SELECT * FROM tournaments ORDER BY id DESC').all()));
app.get('/api/tournaments/:id',(req,res)=>{const t=db.prepare('SELECT * FROM tournaments WHERE id=?').get(req.params.id); if(!t)return res.status(404).json({error:'Not found'}); res.json(t)});
app.post('/api/tournaments',admin,(req,res)=>{const {name,game,entry_fee,prize,slots,start_at}=req.body; if(!name||!game||entry_fee==null||!slots)return res.status(400).json({error:'Missing fields'}); const r=db.prepare('INSERT INTO tournaments(name,game,entry_fee,prize,slots,start_at) VALUES(?,?,?,?,?,?)').run(name,game,entry_fee,prize||'',slots,start_at||''); res.json({id:r.lastInsertRowid})});
app.post('/api/tournaments/:id/register',(req,res)=>{const t=db.prepare('SELECT * FROM tournaments WHERE id=?').get(req.params.id); if(!t||t.status!=='OPEN')return res.status(400).json({error:'Tournament closed'}); const {player_name,uid,team_name,utr}=req.body; if(!player_name||!uid||!utr)return res.status(400).json({error:'Player name, UID and UTR are required'}); const count=db.prepare("SELECT count(*) c FROM registrations WHERE tournament_id=? AND status!='REJECTED'").get(t.id).c; if(count>=t.slots)return res.status(400).json({error:'Slots full'}); const r=db.prepare('INSERT INTO registrations(tournament_id,player_name,uid,team_name,utr) VALUES(?,?,?,?,?)').run(t.id,player_name,uid,team_name||'',utr); res.json({registration_id:r.lastInsertRowid,status:'PENDING'});});
app.post('/api/admin/login',(req,res)=>{if(req.body.password!==SECRET)return res.status(401).json({error:'Wrong password'}); res.json({token:jwt.sign({role:'admin'},SECRET,{expiresIn:'7d'})})});
app.get('/api/admin/registrations',admin,(req,res)=>res.json(db.prepare('SELECT r.*,t.name tournament FROM registrations r JOIN tournaments t ON t.id=r.tournament_id ORDER BY r.id DESC').all()));
app.patch('/api/admin/registrations/:id',admin,(req,res)=>{const {status}=req.body; if(!['VERIFIED','REJECTED','PENDING'].includes(status))return res.status(400).json({error:'Invalid status'}); db.prepare('UPDATE registrations SET status=? WHERE id=?').run(status,req.params.id); res.json({ok:true})});
app.patch('/api/admin/tournaments/:id',admin,(req,res)=>{const {status,room_id,room_password}=req.body; db.prepare('UPDATE tournaments SET status=COALESCE(?,status),room_id=COALESCE(?,room_id),room_password=COALESCE(?,room_password) WHERE id=?').run(status||null,room_id||null,room_password||null,req.params.id); res.json({ok:true})});
app.listen(process.env.PORT||8080,()=>console.log('Suri API running on :8080'));
